name: Build with Composite Action

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android
        with:
          python-version: '3.10'
          buildozer-cmd: 'buildozer android debug'.apk
